server:
  port: 9091

spring:
  application:
    name: APPUSER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: user1
    password: user1
  jpa:
    hibernate:
     ddl-auto: update
     show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.mailtrap.io
    password: 70207628a165b6
    port: 2525
    username: a0dbe590d38dce

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${service-registry:http://localhost:8761/eureka}